apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:   
      containers:
      - name: backend-feed
        image: fredmann1993/api-feed
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - secretRef: 
            name: aws-secret
        - secretRef:
            name: envsecret
      volumes:
      - name: config-dir
        configMap:
         name: envconfigmap
        