apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-user
  labels:
    app: api-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-user
  template:
    metadata:
      labels:
        app: api-user
    spec:   
      containers:
      - name: api-user 
        image: fredmann1993/api-user
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef: 
            name: aws-secret
        - secretRef:
            name: envsecret
      volumes:
      - name: config-dir
        configMap:
         name: envconfigmap
        